CREATE TABLE  taskPrueba (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title TEXT NOT NULL ,
    description TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE  taskPrueba (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

